### PR TITLE
Fix Code Generation with GYB

### LINKED ISSUE #204: env: python2.7: No such file or directory
When running `variants setup` or `variants switch`, many users noticed the non fatal error in the logs:
```shell
env: python2.7: No such file or directory
```

This, because [utils/gyb](https://github.com/Backbase/variants/blob/2fcc461e2a0d741d3a9228cde0689a3bb0be7b5d/utils/gyb) requires it.

Due to this issue Variants will not generate `Secrets` in `Variants.swift` (used when [assigning environment variables to custom config values](https://github.com/Backbase/variants/blob/develop/docs/ENVIRONMENT_VARIABLES.md))

### LINKED ISSUE #240: [iOS] - False positive when generating Variants.swift
### Environment ###
**Variants:**
 - Way of installation: Any
 - Version 1.2.1

**Your machine:**
 - OS: MacOS
 - Processor Apple Silicon

**Project's platform:**
 - Platform: iOS

### Describe the bug ###
This relates to #205, when we rely on custom configs whose `env` option is set to `true` and python 2.7 isn't installed.
`stdout` states that `Variants.swift` has been generated successfully but it isn't.

**Steps to reproduce**
1. Do not have Python 2.7 installed.
2. Have at least 1 custom config setting `env: true` (regardless of the env var existing or not)
3. Execute `switch` command to that variant.
4. Variants prints to stdout that `⚙️  '[...]/Variants/Variants.swift' has been generated with success`.
5. `Variants/` folder doesn't contain `Variants.swift`. 

**Expected behavior**
A clear error message stating what happened and the steps to fix it.

### PR DESCRIPTION
**Pull request by arthurpalves**
### What does this PR do
- When capturing the output of a Bash command, select either `stdout` or `stderr` to be captured.
- Require `python2.7` to run `gyb` and default to a `fatalError` if not available. This prints an appropriate message to the user.
- It defaults to a `fatalError` when generating `Variants.Secrets` if environment variable used by a custom config doesn't exist.

### How can it be tested
- Run `variants switch` or `variants setup` without `python2.7` installed or in your executables path.
- Run `variants switch` or `variants setup` with at least one custom config whose `env: true` but `value` points to a non-existing environment variable.

### Task
Resolves #204 
Resolves #240 

### Checklist:

- [x] I ran `make validation` locally with success
- [x] I have not introduced new bugs
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new errors

### CODE REVIEW

File: Sources/VariantsCore/Factory/iOS/VariantsFileFactory.swift [hunk 1]
```diff
@@ -72,24 +71,48 @@ class VariantsFileFactory {
...
                             variantsGybFile.absolute().description
-                ).run()
+                ).capture(stream: .stderr)
+                let variantsFilePath = "\(variantsGybFile.parent().abbreviate().string)/Variants.swift"
+                handleGybErrors(message: gybStdErr, variantsFilePath: variantsFilePath)
                 
-                logger.logInfo("⚙️  ", item: """
-                    '\(variantsGybFile.parent().abbreviate().string)/Variants.swift' has been generated with success
-                    """, color: .green)
+                logger.logInfo("⚙️  ", item: "'\(variantsFilePath)' has been generated with success", color: .green)
```
Comment (obackbase) [inline Sources/VariantsCore/Factory/iOS/VariantsFileFactory.swift:85]: if there is an error found in `handleGybErrors()` why do we still print that file "has been generated with success"?

Comment (arthurpalves) [reply Sources/VariantsCore/Factory/iOS/VariantsFileFactory.swift:85]: We don't, if any errors it will throw a `fatalError` and stop the execution

File: Sources/VariantsCore/Factory/iOS/VariantsFileFactory.swift [hunk 2]
```diff
@@ -72,24 +71,48 @@ class VariantsFileFactory {
...
+            } else if stdErr.contains("for chunk in chunks(encode(os.environ.get(") {
+                logger.logFatal(item:
+                """
+                We're unable to create 'Variants.Secrets' in '\(variantsFilePath)'.
+                Ensure that custom config values whose `env: true` are actually environment variables.
+                """)
+            } else {
+                logger.logFatal(item: stdErr as Any)
+            }
+        }
```
Comment (GMinucci) [inline Sources/VariantsCore/Factory/iOS/VariantsFileFactory.swift:113]: What about using a `guard` for checking preconditions and a `switch` to do the comparison? The `switch` may be overkill but it will make it easier to add other cases if necessary.
```suggestion
        guard let stdErr = message, !stdErr.isEmpty else { return }
        
        switch stdErr {
        case _ where stdErr.contains("env: python2.7: No such file or directory"):
            logger.logFatal(item:
                """
                We're unable to find a 'python2.7' executable.
                Install 'python2.7' or ensure it's in your executables path and try running this Variants command again.
                Tip:
                    * Install pyenv (brew install pyenv)
                    * Install python2.7 (pyenv install python2.7)
                    * Add "$(pyenv root)/shims" to your PATH
                """)

        case _ where stdErr.contains("for chunk in chunks(encode(os.environ.get("):
            logger.logFatal(item:
                """
                We're unable to create 'Variants.Secrets' in '\(variantsFilePath)'.
                Ensure that custom config values whose `env: true` are actually environment variables.
                """)

        default:
            logger.logFatal(item: stdErr as Any)
        }
```

File: Sources/VariantsCore/Helpers/Bash.swift [hunk 3]
```diff
@@ -34,11 +39,13 @@ struct Bash {
     
     // MARK: - Private
     
-    private func execute(command: String, arguments: [String] = []) throws -> String? {
+    private func execute(command: String, arguments: [String] = [], stream: Stream = .stdout) throws -> String? {
         let process = Process()
-        let pipe = Pipe()
+        let stdoutPipe = Pipe()
+        let stderrPipe = Pipe()
```
Comment (GMinucci) [inline Sources/VariantsCore/Helpers/Bash.swift:45]: It will most probably be over-engineering but should we only check the stream that was selected instead of both all times?

**Review by obackbase — APPROVED** [review]

**Comment by GMinucci** [comment]
@arthurpalves Can we update GYB to latest so we use python3 instead of python2? Since Mac doesn't include python2 by default anymore users need to manually install in the end, so it's better if we install the later version already.
It seems GYB already have support to python3: https://github.com/apple/swift/blob/main/utils/gyb.py

**Comment by arthurpalves** [comment]
@GMinucci @obackbase can one of you try using gyb with python3 support?
I've tried it before changing this PR but it fails every time:
```sh
Traceback (most recent call last):
  File "/usr/local/lib/variants/utils/gyb", line 3, in <module>
    gyb.main()
  File "/usr/local/lib/variants/utils/gyb.py", line 1254, in main
    f.write(execute_template(ast, args.line_directive, **bindings))
  File "/usr/local/lib/variants/utils/gyb.py", line 1124, in execute_template
    ast.execute(execution_context)
  File "/usr/local/lib/variants/utils/gyb.py", line 626, in execute
    x.execute(context)
  File "/usr/local/lib/variants/utils/gyb.py", line 712, in execute
    result = eval(self.code, context.local_bindings)
  File "/Users/arthura/Projects/PERSONAL/variants/samples/ios/Proj/Proj/Variants/Variants.swift.gyb", line 38, in <module>
    %{ salt = [ord(byte) for byte in os.urandom(64)] }%
  File "/Users/arthura/Projects/PERSONAL/variants/samples/ios/Proj/Proj/Variants/Variants.swift.gyb", line 38, in <listcomp>
    %{ salt = [ord(byte) for byte in os.urandom(64)] }%
TypeError: ord() expected string of length 1, but int found
```

**Comment by arthurpalves** [comment]
@GMinucci had the chance to check this?

**Comment by GMinucci** [comment]
This PR also fixes #240

**Review by GMinucci — APPROVED** [review]
