### PR TITLE
fix/signing-config-setup

### LINKED ISSUE #214: Some signing configurations not automatically set in Xcode 14
### Environment ###
**Variants:**
 - Way of installation: All
 - Version 1.1.3

**Your machine:**
 - OS: macOS
 - Processor: M1

**Project's platform:**
 - Platform: iOS

### Describe the bug ###
 When running `variants setup` on a new project, with a proper signing configuration, the profile is loaded and properly set in Xcode but the team ID and signing certificate fields are left empty.
 It also doesn't set signing to manual automatically.

**Steps to reproduce**
1. Go to a new project generated with Xcode 14+
2. Execute command `variants setup` with a valid `variants.yml`
3. In Xcode, see that Signing mode is still set to automatic.
4. Set signing mode to manual, manually.
5. Run `variants setup` again.
6. See that team ID and signing certificate fields are empty, although the provisioning profile is correctly set.

**Expected behavior**
- `variants setup` should change signing mode to manual if a signing configuration is provided in `variants.yml`.
- `variants setup` should properly set a Team ID and Signing Certificate if a signing configuration is provided in `variants.yml`.

### LINKED ISSUE #215: Updates to signing configuration
## Background
- The .pbxproj is updated so that it reads information provided by Variants, this happens as part of the `setup` command.
- If, at the time of running `variants setup`, a signing configuration isn't provided or is incomplete (i.e.: not providing `match_url`), Xcode will still use manually specified settings for signing.
- If adding a signing configuration to `variants.yml` after running `setup`, running `variants switch` will not make changes to `.pbxproj`.

## Solution

- Modify `PROVISIONING_PROFILE_SPECIFIER`, `CODE_SIGN_STYLE` and `CODE_SIGN_IDENTITY` to Variants' provided data not only during `variants setup` but also during `variants switch`, to ensure its effect even if a signing configuration is specified at a later time.

- This allows for supporting `Automatic` signing method as well. Given a new property to each variant, `signing_method` (`automatic` or `manual`) we can support both cases for individual variants.

### PR DESCRIPTION
**Pull request by arthurpalves**
### What does this PR do
- Removes the runtime error when `signing` configuration is `nil` and, instead, maintains the project's signing settings as is (i.e.: in case of automatic signing)
- Adds/adjusts signing configuration when switching variants, not only during setup.
- When adding/adjusting signing configuration also include `CODE_SIGN_STYLE` and `CODE_SIGN_IDENTITY`
- Makes `updateSigningConfig` an optional step.
- Removes the necessity to have a `matchURL` parameter in the signing configuration, thus enabling locally installed provisioning profiles and certs

### How can it be tested
1. Setup a new project using a `variants.yml` without a `signing` configuration. This should no longer fail. Instead, it should setup everything but maintain the existing signing config in Xcode.
2. Add a signing configuration to your `variants.yml` (either global or variant's specific) and switch variants. This should now modify the project's signing config in Xcode.

### Task
resolves #214
resolves #215 

### Checklist:

- [x] I ran `make validation` locally with success
- [x] I have not introduced new bugs
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new errors

### CODE REVIEW

File: Sources/VariantsCore/Factory/iOS/XCConfigFactory.swift [hunk 1]
```diff
@@ -178,18 +170,41 @@ class XCConfigFactory: XCFactory {
...
         }
     }
+
+    private func updateSigningConfig(
+        for variant: iOSVariant,
+        inTarget target: NamedTarget,
+        projectPath: Path
+    ) {
+        guard
+            variant.signing?.matchURL != nil,
```
[the remark this answers is not in the document]
Comment (arthurpalves) [reply Sources/VariantsCore/Factory/iOS/XCConfigFactory.swift:180]: You're right, I'll remove this.

**Comment by arthurpalves** [comment]
Follow up: Solving the one unit test that fails once we split the signing config setup

**Comment by backbaseoss** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Copyright header is missing in files: Sources/VariantsCore/Factory/iOS/XCConfigFactory.swift</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against e183b7b106d1194d5989b7d46f9eeb955f846faa
</p>

File: Tests/VariantsCoreTests/XcodeProjFactoryTests.swift [hunk 2]
```diff
@@ -48,7 +48,8 @@ class XcodeProjFactoryTests: XCTestCase {
             variant: variant,
             xcodeProj: xcodeProjectPath.description,
             configPath: Path(""),
-            addToXcodeProj: false
+            addToXcodeProj: false,
+            updateSigningConfig: false
```
Comment (dubeboy) [inline Tests/VariantsCoreTests/XcodeProjFactoryTests.swift:52]: can we remove this param `updateSigningConfig` and rely on `iOSVariant` as this is what actually determines if the signing configs will be added because `updateSigningConfig` is always true

File: Sources/VariantsCore/Factory/iOS/XCConfigFactory.swift [hunk 3]
```diff
@@ -102,13 +99,19 @@ class XCConfigFactory: XCFactory {
         if addToXcodeProj ?? false {
             addToXcode(xcodeConfigPath, toProject: xcodeProjPath, sourceRoot: configPath, target: target, variant: variant)
         }
-        
+
+        /*
+         * Adjust signing configuration in project.pbxproj
+         */
+        if updateSigningConfig ?? false {
```
Comment (dubeboy) [inline Sources/VariantsCore/Factory/iOS/XCConfigFactory.swift:106]: This if statement will only be false in tests

**Review by dubeboy — APPROVED** [review]

**Review by GMinucci — APPROVED** [review]
